import { Box, Button, Flex, Img, Text } from "@chakra-ui/react";
import Lottie from "react-lottie";
import moment from "moment";
import "moment-duration-format";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

import animationData from "../public/love.json";

const Home: NextPage = () => {
	const [imageIndex, setImageIndex] = useState(0);
	const images = ["/1.jpg", "/2.jpeg", "/3.jpeg"];
	const [secret, setSecret] = useState(0);

	return (
		<Box overflowX="hidden">
			<Head>
				<title>❤️</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.svg" />
			</Head>
			<Images image={images[imageIndex]} key={images[imageIndex]} />
			<CountDown />
			<Flex justify="center">
				<Button
					size="sm"
					bgColor="transparent"
					_hover={{ bgColor: "transparent" }}
					borderRadius="full"
					onClick={() => {
						setImageIndex(
							imageIndex === images.length - 1
								? 0
								: imageIndex + 1
						);
						setSecret(secret + 1);
					}}
				>
					❤️
				</Button>
			</Flex>
			<Box p={5} display={secret >= 30 ? "inherit" : "none"}>
				<Text textAlign="center" color="gray.500" mb="10px">
					❤️ Você descobriu um segredo! ❤️
				</Text>
				<Text color="gray.500">
					&emsp;De todas as mulheres que eu conheci nesse mundo você é
					a mais maravilhosa, especial e perfeita. Suas
					características, seu jeitinho, sua delicadeza me encantam
					sempre que olho pra você, ouço sua voz ou simplesmente penso
					em você. Doce como mel e fofa como um algodão, você me tira
					do sério, me levando a lugares que nem imaginava alcançar, a
					um nível de paixão que excede as expectativas. Te amo com
					todo o meu coração, e quero te amar cada vez mais, como
					Cristo amou a Igreja e se entregou por ela. Com você eu
					consigo entender esse tipo de amor, e almejar aperfeiçoa-lo
					a ponto de ser perfeito da mesma forma. Que esse site fique
					no ar por muito e muito tempo, a cada segundo aumentando o
					nosso amor. E que a gente volte aqui quando tiver 3, 5, 10,
					50, 70 anos, e perceba que a cada ano que passa o nome amor,
					de fato, aumenta.
				</Text>
				<Text color="gray.500" textAlign="center" mt="10px">
					Te amo minha linda. Pra sempre minha pricesa. ❤️
				</Text>
			</Box>
		</Box>
	);
};

function Images({ image }: any) {
	const defaultOptions = {
		loop: false,
		autoplay: true,
		animationData: animationData,
	};

	return (
		<Box pos="relative">
			<Flex left={{ base: "auto", md: "33%" }} pos="absolute" h="full">
				<Lottie
					options={defaultOptions}
					isClickToPauseDisabled
					height={"100%"}
					width={"100%"}
				/>
			</Flex>
			<Flex justify="center" align="center" w="100vw" h="70vh" mb={10}>
				<Img src={image} h="full" mt="30px" />
			</Flex>
		</Box>
	);
}

interface props {
	years: number;
	months: number;
	days: number;
	hours: number;
	minutes: number;
	seconds: number;
}

function CountDown() {
	const [timeDiff, setTimeDiff] = useState<props>();

	useEffect(() => {
		let secTimer = setInterval(() => {
			var starts = moment("2020-09-25 12:53:12");
			var ends = moment();
			var duration = moment.duration(ends.diff(starts)) as any;
			setTimeDiff(duration._data);
		}, 1000);

		return () => clearInterval(secTimer);
	}, []);
	return (
		<>
			<Text textAlign="center" fontWeight="light" color="gray.500">
				Juntos
			</Text>
			<Text textAlign="center">
				{timeDiff?.years} {timeDiff?.years === 1 ? "ano" : "anos"}
				{", "}
				{timeDiff?.months} {timeDiff?.months === 1 ? "mês" : "meses"}
				{", "}
				{timeDiff?.days} {timeDiff?.days === 1 ? "dia" : "dias"}
			</Text>
			<Text textAlign="center">
				{timeDiff?.hours} {timeDiff?.hours === 1 ? "hora" : "horas"}
				{", "}
				{timeDiff?.minutes}{" "}
				{timeDiff?.minutes === 1 ? "minuto" : "minutos"} e{" "}
				{timeDiff?.seconds}{" "}
				{timeDiff?.seconds === 1 ? "segundo" : "segundos"}
			</Text>
		</>
	);
}

export default Home;
